apiVersion: delta.se/v1alpha1
kind: Component
metadata:
  name: badger
  description: a real badger
  annotations:
    jenkins.io/github-folder: 'user-sync'
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - badger
    - badgerLights
    - badger-hello-world
