apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: badger
  description: test project
  tags:
    - java
    - data
spec:
  type: library
  lifecycle: experimental
  owner: delta projects
